apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: anythink-backend-rails
  name: anythink-backend-rails
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: anythink-backend-rails
