apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Values.database.serviceName }}-migration-job
  name: {{ .Values.database.serviceName }}-migration-job
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.database.serviceName }}-migration-job
    spec:
      containers:
        - command:
            - exec
            - rails
            - db:migrate
          name: {{ .Values.database.serviceName }}-migration-job
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.connectionProtocol}}{{ .Values.database.env.userName}}:@{{ .Values.database.serviceName }}:{{ .Values.database.servicePort }}"
            - name: RAILS_ENV
              value: development
            - name: PORT
              value: "{{ .Values.backend.containerPort }}"
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
      restartPolicy: Never
