apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-rails
  name: postgres-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-rails
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-rails
    spec:
      containers:
        - image: postgres
          image: "{{ .Values.postgresdb.image.repository }}:{{ .Values.postgresdb.image.tag }}"
          name: postgres-rails
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          imagePullPolicy: {{ .Values.postgresdb.image.pullPolicy }}
          ports:
            - containerPort: 5433
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: postgres-rails-0
      restartPolicy: Always
      volumes:
        - name: postgres-rails-0
          persistentVolumeClaim:
            claimName: postgres-rails-0
