apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-rails-0
  name: postgres-rails-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
