apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-rails
  name: postgres-rails
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-rails
